package dev.vt.persistence.model.enums;

public enum SemesterType {
    BS_Comp_I,
    BS_Comp_II,
    BS_Comp_III,
    BS_Comp_IV,
    BS_Comp_V,
    BS_Comp_VI,
    BS_AI_I,
    BS_AI_II,
    BS_AI_III,
    BS_AI_IV,
    BS_AI_V,
    BS_AI_VI,
    BS_IT_I,
    BS_IT_II,
    BS_IT_III,
    BS_IT_IV,
    BS_IT_V,
    BS_IT_VI,
    MS_Comp_I,
    MS_Comp_II,
    MS_Comp_III,
    MS_Comp_IV,
    MS_AI_I,
    MS_AI_II,
    MS_AI_III,
    MS_AI_IV,
    MS_IT_I,
    MS_IT_II,
    MS_IT_III,
    MS_IT_IV,
    Diplma_DS_I,
    Diplma_DS_II,
}
